name: Build 

on: [ push, pull_request]


  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build 
        shell: bash
        run: gcc main.c

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            a.out
            LICENSE







