name: Build 

on: [ push, pull_request]


  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build 
        shell: bash
        run: gcc main.c

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-binary-artifact
          path: a.out

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-binary-artifact
          path: artifacts

